/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Metodos.Metodo_Cesar;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Damián
 */
public class Vista_Cifrado extends javax.swing.JFrame {

    Metodo_Cesar mc = new Metodo_Cesar();

    /**
     * Creates new form Vista_Cifrado
     */
    public Vista_Cifrado() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_texto = new javax.swing.JTextField();
        txt_Cifrado = new javax.swing.JTextField();
        btn_cifrar = new javax.swing.JButton();
        cbox_ubi = new javax.swing.JComboBox<String>();
        btn_Decifrar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        btn_copiar = new javax.swing.JButton();
        btn_copiar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_texto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_textoKeyTyped(evt);
            }
        });

        txt_Cifrado.setEditable(false);

        btn_cifrar.setText("Cifrar");
        btn_cifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cifrarActionPerformed(evt);
            }
        });

        cbox_ubi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));
        cbox_ubi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_ubiActionPerformed(evt);
            }
        });

        btn_Decifrar.setText("Decifrar");
        btn_Decifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DecifrarActionPerformed(evt);
            }
        });

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        btn_copiar.setText("Copiar");
        btn_copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_copiarActionPerformed(evt);
            }
        });

        btn_copiar1.setText("Pegar");
        btn_copiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_copiar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(cbox_ubi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btn_copiar)
                        .addGap(67, 67, 67)
                        .addComponent(btn_copiar1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_Cifrado)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_cifrar)
                                .addGap(45, 45, 45)
                                .addComponent(btn_limpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(btn_Decifrar)))
                        .addGap(86, 86, 86))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox_ubi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cifrar)
                    .addComponent(btn_Decifrar)
                    .addComponent(btn_limpiar))
                .addGap(48, 48, 48)
                .addComponent(txt_Cifrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_copiar)
                    .addComponent(btn_copiar1))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cifrarActionPerformed
        // TODO add your handling code here:
//        String PMayus = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
//        String PMinus = "abcdefghijklmnopqrstuvwxyz";
        //   String box = (String) cbox_ubi.getSelectedItem();
        if (txt_texto.getText().length() != 0 && cbox_ubi.getSelectedItem().toString().length() > -1
                && cbox_ubi.getSelectedItem().toString() != "--") {

            // mc.Cifrar(txt_texto, txt_ubi, txt_Cifrado);
            mc.Cifrar2(txt_texto, cbox_ubi, txt_Cifrado);

        } else {
            JOptionPane.showMessageDialog(null, "Campos Vacios");

        }
    }//GEN-LAST:event_btn_cifrarActionPerformed

    private void btn_DecifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DecifrarActionPerformed

        if (txt_texto.getText().length() != 0 && cbox_ubi.getSelectedItem().toString().length() > -1
                && cbox_ubi.getSelectedItem().toString() != "--") {

            mc.Descifrar2(txt_texto, cbox_ubi, txt_Cifrado);

        } else {
            JOptionPane.showMessageDialog(null, "Campos Vacios");

        }


    }//GEN-LAST:event_btn_DecifrarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed

        txt_texto.setText("");
        cbox_ubi.setSelectedItem("--");
        txt_Cifrado.setText("");

    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void txt_textoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_textoKeyTyped

//        char c= evt.getKeyChar();
//        
//        if((c<'a'|| c>'z')&& (c<'A'|| c>'Z'))evt.consume();
        Character c = evt.getKeyChar();

        if (!Character.isLetter(c) && c != KeyEvent.VK_SPACE) {
            evt.consume();
        }


    }//GEN-LAST:event_txt_textoKeyTyped

    private void cbox_ubiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_ubiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_ubiActionPerformed

    private void btn_copiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_copiarActionPerformed

        mc.copiar(txt_Cifrado.getText());
        txt_texto.setText("");
        cbox_ubi.setSelectedItem("--");
        txt_Cifrado.setText("");
    }//GEN-LAST:event_btn_copiarActionPerformed

    private void btn_copiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_copiar1ActionPerformed
        txt_texto.setText("");
        cbox_ubi.setSelectedItem("--");
        txt_Cifrado.setText("");
        txt_texto.paste();
    }//GEN-LAST:event_btn_copiar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Cifrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Cifrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Cifrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Cifrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Cifrado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Decifrar;
    private javax.swing.JButton btn_cifrar;
    private javax.swing.JButton btn_copiar;
    private javax.swing.JButton btn_copiar1;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JComboBox<String> cbox_ubi;
    private javax.swing.JTextField txt_Cifrado;
    private javax.swing.JTextField txt_texto;
    // End of variables declaration//GEN-END:variables
}
